theme: jekyll-theme-minimal
logo: ./figures/Chris.jpeg
title: Zenan Li's HomePage
description: Thanks for visiting my homepage and welcome to contact me at:<br /><br /><a href="mailto:Emiyalzn@gmail.com">ðŸ“® Emiyalzn@gmail.com</a><br />
